---
title: "Homework 3"
author: "Caesar (Zexuan) Li"
date: "2/26/2018"
output: html_document
---



## Q1 LA City Employee Payroll

The `/home/m280-data/la_payroll/LA_City_Employee_Payroll.csv` file on teaching server contains payroll information of LA City employees in years 2013-2017. It was downloaded from [LA City Controller's Office](https://controllerdata.lacity.org/Payroll/City-Employee-Payroll/pazn-qyym). Make a Shiny app to facilitate exploratory data analysis. 

# Q1

1. For efficiency of the Shiny app, you should first pre-process, pare down, tidy, and save the data, e.g., as a compressed RDS file, to be used in the app.

    ```{r}
    if (!"tidyverse" %in% rownames(installed.packages()))  
          install.packages("tidyverse", repos="http://cran.rstudio.com/")
    library(tidyverse)
    
    setwd("/home/m280-data/la_payroll/")
    payroll <- read_delim("LA_City_Employee_Payroll.csv", 
                          col_names = TRUE, delim = ",")
    
    currencies <- c(8:14, 16:24, 30:33)
    payroll <- payroll %>% 
      mutate_at(funs(str_sub(.,start = 2)), .vars = vars(currencies)) %>% 
      mutate_at(funs(as.double(.)), .vars = vars(currencies)) %>%
      mutate_at(funs(as.character(.)), .vars = vars(4, 5, 25, 27))
    
    setwd("/home/zexuan55/biostat-m280-2018-winter/hw3/hw3_shiny/data")
    write_rds(payroll, "payroll.rds")
    ```

    Answer: read in data set with dplyr as required. Data is already tiday. Converted currancy characters to doubles for shiny app computations.

2. **Total payroll by LA City**. Visualize the total LA City payroll of each year, with breakdown into base pay, overtime pay, and other pay.

    Answer: yes I did. It's in the Shiny app's first tab.

3. **Who earned most?** Visualize the payroll information (total payment with breakdown into base pay, overtime pay, and other pay, Department, Job Title) of the top $n$ highest paid LA City employees in a specific year. User specifies $n$ (default 10) and year (default 2017).

    Answer: yes I did. It's in the Shiny app's second tab.

4. **Which departments earn most?** Visualize the mean or median payroll, with breakdown into base pay, overtime pay, and other pay, of top $n$ earning departments. User specifies $n$ (default 5), year (default 2017), and method (mean or median, default median).

    Answer: yes I did. It's in the Shiny app's third tab.

5. **Which departments cost most?** Visualize the total payroll, with breakdown into base pay, overtime pay, and other pay, of top $n$ expensive departments. User specifies $n$ (default 5) and year (default 2017).

    Answer: yes I did. It's in the Shiny app's fourth tab.

6. Visualize any other information you are interested in.

    Answer: yes I did. I added a box plot for top-earning employees by years and it's in the Shiny app's fifth tab. Users control how many top employees to be included.

7. Publish your Shiny app to <https://www.shinyapps.io> and share the link.
    
    Answer: yes I did. The link is pasted down below.
    [linked phrase]( https://caeseriousli.shinyapps.io/hw3_shiny/)

## Q2 LA City Parking War

# Q2

The SQLite database `/home/m280-data/la_parking/LA_Parking_Citations.sqlite` on teaching server contains information about parking tickets in LA City. It was downloaded from [LA Open Data Portal](https://data.lacity.org/A-Well-Run-City/Parking-Citations/wjz9-h9np). Connect to the database and answer following questions using plots and summary statistics. In this exercise, you are **not** allowed to load whole data into memory. Use the _transform in database, plot in R_ strategy.

1. How many tickets are in this data set? Which time period do these tickets span? Which years have most data?

    ```{R}
    if (!"DBI" %in% rownames(installed.packages()))  
          install.packages("DBI", repos="http://cran.rstudio.com/")
    if (!"RSQLite" %in% rownames(installed.packages()))  
          install.packages("RSQLite", repos="http://cran.rstudio.com/")
    #if (!"lubridate" %in% rownames(installed.packages()))  
         # install.packages("lubridate", repos="http://cran.rstudio.com/")
    
    library("DBI")
    library("RSQLite")
    #library("lubridate")
    db <- dbConnect(RSQLite::SQLite(), 
                    dbname = 
                    "/home/m280-data/la_parking/LA_Parking_Citations.sqlite")
    dbListTables(db)
    tix <- dplyr::tbl(db, "Latix")
    total <- tix %>% tally() %>% collect()
    
    span <- tix %>%
      select(Issue_DateTime) %>%
      summarise(min = min(Issue_DateTime, na.rm = T), 
                max = max(Issue_DateTime, na.rm = T)) %>%
      collect()
    
    yr <- tix %>%
      mutate(Issue_DateTime = 
             datetime(Issue_DateTime, 'unixepoch', 'localtime')) %>%
      mutate(year = strftime('%Y', Issue_DateTime)) %>%
      group_by(year) %>%
      summarize("count" = n()) %>%
      arrange(desc(count)) %>%
      head(1) %>%
      collect()
    
    cat("Number of observations: ", as.double(total), "\n",
        "Range: \nEarliest ", 
        as.character(as.POSIXct(span$min, origin="1970-01-01")), "\n",
        "Latest ", 
        as.character(as.POSIXct(span$max, origin="1970-01-01")), "\n",
        "Year that has the most data: ", 
        as.double(yr$year), "\n", sep = "")
    ```

    Answer: all results are printed above, by code above. Note that all queries ignored missing values.

2. When (which hour, weekday, month day, and month) are you most likely to get a ticket and when are you least likely to get a ticket?

    ```{R}
    db2 <- dbConnect(RSQLite::SQLite(), 
                    dbname = 
                    "/home/m280-data/la_parking/LA_Parking_Citations_Extra.sqlite")
    tix2 <- dplyr::tbl(db2, "Latix")
    
    hr <- tix2 %>%
      group_by(Issue_Hour) %>%
      summarize("count" = n()) %>%
      arrange(desc(count)) %>%
      filter(!is.na(Issue_Hour)) %>%
      collect()
    
    wd <- tix2 %>%
      group_by(Issue_Wday) %>%
      summarize("count" = n()) %>%
      arrange(desc(count)) %>%
      filter(!is.na(Issue_Wday)) %>%
      collect()
    
    md <- tix2 %>%
      group_by(Issue_Day) %>%
      summarize("count" = n()) %>%
      arrange(desc(count)) %>%
      filter(!is.na(Issue_Day)) %>%
      collect()
    
    # filtered out the oldest data in 2010 in order to keep the analysis accurate
    ym <- tix2 %>%
      filter(!(Issue_Year == 2010 & Issue_Month <= 12 & Issue_Day <= 29)) %>%
      group_by(Issue_Month) %>%
      summarize("count" = n()) %>%
      arrange(desc(count)) %>%
      filter(!is.na(Issue_Month)) %>%
      collect()
    
    cat("Most likely: \n",
        "Hour of the day: ", as.character(hr[1, 1]), "\n",
        "Week day: ", as.character(wd[1, 1]), "\n",
        "Day of the month: ", as.character(md[1, 1]), "\n",
        "Month of the year: ", as.character(ym[1, 1]), "\n",
        "\nLeast likely: \n",
        "Hour of the day: ", as.character(hr[nrow(hr), 1]), "\n",
        "Week day: ", as.character(wd[nrow(wd), 1]), "\n",
        "Day of the month: ", as.character(md[nrow(md), 1]), "\n",
        "Month of the year: ", as.character(ym[nrow(ym), 1]), "\n", sep = "")
    ```

    Answer: all results are printed above. Note that for most/least likely month of the year, if we included all of the data, monthly frequencies of all observations would be weighted more towards Oct-Dec, since the data started in Oct 2010 and ended in Dec 2017 and therefore we have an extra "piece of a year" that has only Oct-Dec. Therefore I decided to filter out the data from Oct-Dec in 2010, therefore obtaining evenly weighted frequencies.

3. Which car makes received most citations?

    ```{R}
    makes <- tix2 %>%
      group_by(Make) %>%
      summarize("count" = n()) %>%
      arrange(desc(count)) %>%
      filter(!is.na(Make)) %>%
      head(1) %>%
      collect()
    
    cat("Car make that received most citations: ", 
        as.character(makes[1,1]), "\n", sep = "")
    ```

    Answer: the car make that received most of the citations is printed above (Toyota).

4. How many different colors of cars were ticketed? Which color attracted most tickets?

    ```{R}
    cl <- tix2 %>%
      group_by(Color) %>%
      summarise("count" = n()) %>%
      arrange(desc(count)) %>%
      filter(!is.na(Color)) %>%
      collect()
    
    cat("Number of different colors of cars: ", 
        as.character(nrow(cl)), "\n",
        "Color that attracted most tickets: ", 
        as.character(cl[1, 1]), "\n", sep = "")
    ```

    Answer: as printed above. There are 65 different car colors that were ticketed, among with Black cars received most of the tickets.

5. What are the most common ticket types?

    ```{R}
    tt <- tix2 %>%
      group_by(Violation_Description) %>%
      summarise("count" = n()) %>%
      arrange(desc(count)) %>%
      filter(!is.na(Violation_Description)) %>%
      collect()
    
    cat("Most common ticket type: ", 
        as.character(tt[1, 1]), "\n", sep = "")
    ```

6. How much money was collected on parking tickets in 2015 and 2016?

    ```{R}
    money <- tix2 %>%
      filter(Issue_Year == 2015 | Issue_Year == 2016) %>%
      summarise(tot = sum(Fine_amount, na.rm = T)) %>%
      collect()
    
    cat("Total fine collected in 2015 and 2016 ", 
        as.character(money$tot), "\n", sep = "")
    ```

    Answer: as printed above the total money collected in those two years is $274242930.

7. Visualize any other information you are interested in.

    ```{R}
    if (!"ggplot2" %in% rownames(installed.packages()))  
      install.packages("ggplot2", repos="http://cran.rstudio.com/")
    library(ggplot2)
    
    ym <- as.data.frame(ym)
    ym$count = ym$count / 7
    ggplot(ym, aes(x = as.factor(ym$Issue_Month), y = ym$count)) +
      geom_col() +
      labs(title = "Average Monthly Number of Citations",
           subtitle = "Starting from 2010-12-29",
           x = "Month",
           y = "Average Number of Citations")
    ```

    Answer: we're plotting Average Monthly Number of Citations. Note that for average monthly citations I divided total frequencies by 7 because each month of the year occurred 7 times from 2010 to 2017. 
